
import { GoogleGenAI } from "@google/genai";

/**
 * Generates a meme image using Gemini 2.5 Flash Image.
 * We append the brand description to ensure the jug remains consistent.
 */
export const generateMemeImage = async (
  userPrompt: string
): Promise<string> => {
  // Always use the most up-to-date API key from the environment.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const brandDescription = "A clear 5-gallon water cooler jug with blue handle and blue cap, filled with thick white liquid, realistic, cinematic lighting, 8k, professional photography.";
  const fullPrompt = `${userPrompt}, featuring ${brandDescription}`;
  
  // Use the recommended model for general image generation tasks.
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          text: fullPrompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1"
      },
    },
  });

  if (!response.candidates?.[0]?.content?.parts) {
    throw new Error("The jug machine failed to respond.");
  }

  // Find the image part in the response parts as instructed in the guidelines.
  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64EncodeString: string = part.inlineData.data;
      return `data:image/png;base64,${base64EncodeString}`;
    }
  }

  throw new Error("No image was generated by the jug machine.");
};

export const randomMemePrompts = [
  "Elon Musk triumphantly holding the branded 5-gallon jug on a stage at a tech keynote",
  "Donald Trump pointing at the branded 5-gallon jug during a rally with a serious face",
  "Joe Rogan sitting in his studio with the branded 5-gallon jug on the desk",
  "A realistic Viking warrior protecting the 5-gallon jug during a storm",
  "An astronaut floating in the ISS with the jug drifting in zero gravity",
  "A secret agent in a sharp suit running through a city while carrying the 5-gallon jug",
  "A hyper-realistic golden retriever sitting next to the 5-gallon jug on a porch",
  "A high-end luxury fashion model posing with the jug for a magazine cover",
  "The jug sitting on the center of a high-stakes poker table in a dark casino",
  "A cyberpunk hacker surrounded by screens with the 5-gallon jug plugged into a computer"
];
